### ISSUE TITLE
Build on Ubuntu

### ISSUE THREAD

**Issue by MmdMbd** [anatoltrush/RadarVisual#1]
Hi!
first for all thanks for your great job!!
I'm trying to build the source code on ubuntu, but I can't find any cmakelistk file in the project.
I've searched on the internet, but didn't find anything useful.
Since I'm a little bit new on ubuntu, can you provide me anything to build this project?

**Comment by anatoltrush** [comment]
Hello!
There are no any cmake files.
To build the project you have to install Qt.
Moreover have to build & install ZMQ library before

**Comment by MmdMbd** [comment]
Thanks for your help.

**Comment by FlyingAnt2018** [comment]
> ZMQ



> Moreover have to build & install ZMQ library before

Hi, is there any pipeline of install ?  And i also want to build the project on ubuntu,thanks.

**Comment by anatoltrush** [comment]
Hi, you should look for the installation pipeline in the ZMQ pages https://github.com/zeromq

**Comment by anatoltrush** [comment]
Unfortunately project not tested with usbcan64. Only with PCAN-USB
