### ISSUE TITLE
Questions regarding how the .log file is interpreted

### ISSUE THREAD

**Issue by JuanFelipeSerafim** [anatoltrush/RadarVisual#2]
Hello! The possibilities for using the application are excellent, but I have doubts regarding how the .log file is read by the application.
Thank you for your attention.

**Comment by anatoltrush** [comment]
What's wrong with file reading?
Any suggestions?

**Comment by JuanFelipeSerafim** [comment]
The question was how the .log file was read by the application because I was considering that I would not be able to connect the radar directly to the application.  But I tested it today and it worked perfectly!  Thank you very much for developing this application!

**Comment by anatoltrush** [comment]
You're welcome ;-)
