### ISSUE TITLE
Using Neovi FIre 2 with RadarVisual

### ISSUE THREAD

**Issue by LucasBarbosa156** [anatoltrush/RadarVisual#3]
Hello, I have a question. I want to use CanVisual to visualize data from an ARS-408 radar using the CAN channels of the Neovi Fire 2. Do you have any tips on how to do this? I’ve been trying to figure it out but haven’t had any success so far. I only tried connecting it to the computer, but nothing appeared in CanVisual, not even the CAN channels through which the radar data was being transmitted. I also tried using Vehicle Spy 3 in the background to ensure that the ARS-408 radar data was arriving correctly and verified that it was, but still, nothing appeared in CanVisual.

**Comment by anatoltrush** [comment]
CanVisual is not supporting this device. You can use PEAK-CAN for visualizing radar data.
